"""postgres_baseline_all_tables

Revision ID: 0001
Revises: 
Create Date: 2026-05-27 01:05:05.275912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_audit_events',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_supabase_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_events_created_at'), 'platform_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_audit_events_event_type'), 'platform_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_platform_audit_events_tenant_id'), 'platform_audit_events', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('demo_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tenant_memberships',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supabase_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('source', sa.String(), server_default='manual', nullable=False),
    sa.Column('created_by_supabase_user_id', sa.UUID(), nullable=True),
    sa.Column('is_demo_seeded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False)
    op.create_table('segments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('segment_key', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('year_group', sa.String(), nullable=False),
    sa.Column('ac_type', sa.String(), nullable=False),
    sa.Column('room_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('room_size IN (2, 3, 4)', name='ck_segments_room_size'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_segments_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_segments_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'gender', 'year_group', 'ac_type', 'room_size', name='uq_segments_workspace_dimensions'),
    sa.UniqueConstraint('workspace_id', 'segment_key', name='uq_segments_workspace_segment_key')
    )
    op.create_index(op.f('ix_segments_tenant_id'), 'segments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_segments_workspace_id'), 'segments', ['workspace_id'], unique=False)
    op.create_table('workspace_form_links',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('public_form_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_form_token')
    )
    op.create_index(op.f('ix_workspace_form_links_tenant_id'), 'workspace_form_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workspace_form_links_workspace_id'), 'workspace_form_links', ['workspace_id'], unique=False)
    op.create_table('matching_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('target_segment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fairness_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by_supabase_user_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_email', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("scope IN ('segment', 'all_ready_segments')", name='ck_matching_runs_scope'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_matching_runs_status'),
    sa.ForeignKeyConstraint(['target_segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_matching_runs_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_matching_runs_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_matching_runs_created_at'), 'matching_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_matching_runs_status'), 'matching_runs', ['status'], unique=False)
    op.create_index(op.f('ix_matching_runs_target_segment_id'), 'matching_runs', ['target_segment_id'], unique=False)
    op.create_index(op.f('ix_matching_runs_tenant_id'), 'matching_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_matching_runs_workspace_id'), 'matching_runs', ['workspace_id'], unique=False)
    op.create_table('rooms',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), server_default='uploaded', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('uploaded', 'generated')", name='ck_rooms_source'),
    sa.CheckConstraint('capacity IN (2, 3, 4)', name='ck_rooms_capacity'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_rooms_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_rooms_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'segment_id', 'room_id', name='uq_rooms_workspace_segment_room')
    )
    op.create_index(op.f('ix_rooms_segment_id'), 'rooms', ['segment_id'], unique=False)
    op.create_index(op.f('ix_rooms_tenant_id'), 'rooms', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rooms_workspace_id'), 'rooms', ['workspace_id'], unique=False)
    op.create_table('students',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('year_group', sa.String(), nullable=False),
    sa.Column('ac_type', sa.String(), nullable=False),
    sa.Column('room_size', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('phone_last4', sa.String(length=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('room_size IN (2, 3, 4)', name='ck_students_room_size'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_students_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_students_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'admission_number', name='uq_students_workspace_admission')
    )
    op.create_index(op.f('ix_students_phone_last4'), 'students', ['phone_last4'], unique=False)
    op.create_index(op.f('ix_students_segment_id'), 'students', ['segment_id'], unique=False)
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_students_workspace_id'), 'students', ['workspace_id'], unique=False)
    op.create_table('form_responses',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('submitted_admission_number', sa.String(), nullable=False),
    sa.Column('submitted_phone_last4', sa.String(length=4), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('invalid_reason', sa.Text(), nullable=True),
    sa.Column('q1_raw', sa.Text(), nullable=True),
    sa.Column('q2_raw', sa.Text(), nullable=True),
    sa.Column('q3_raw', sa.Text(), nullable=True),
    sa.Column('q4a_raw', sa.Text(), nullable=True),
    sa.Column('q4b_raw', sa.Text(), nullable=True),
    sa.Column('q5a_raw', sa.Text(), nullable=True),
    sa.Column('q5b_raw', sa.Text(), nullable=True),
    sa.Column('q6_raw', sa.Text(), nullable=True),
    sa.Column('q7_raw', sa.Text(), nullable=True),
    sa.Column('q8_raw', sa.Text(), nullable=True),
    sa.Column('q9_raw', sa.Text(), nullable=True),
    sa.Column('q10_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("validation_status IN ('valid', 'invalid')", name='ck_form_responses_status'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_form_responses_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_form_responses_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_student_id'), 'form_responses', ['student_id'], unique=False)
    op.create_index(op.f('ix_form_responses_submitted_at'), 'form_responses', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_form_responses_tenant_id'), 'form_responses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_form_responses_validation_status'), 'form_responses', ['validation_status'], unique=False)
    op.create_index('ix_form_responses_workspace_admission_submitted', 'form_responses', ['workspace_id', 'submitted_admission_number', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_form_responses_workspace_id'), 'form_responses', ['workspace_id'], unique=False)
    op.create_table('pair_scores',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('matching_run_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('student_a_id', sa.UUID(), nullable=False),
    sa.Column('student_b_id', sa.UUID(), nullable=False),
    sa.Column('pair_score', sa.Float(), nullable=False),
    sa.Column('factor_breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pair_score >= 0.0 AND pair_score <= 1.0', name='ck_pair_scores_range'),
    sa.CheckConstraint('student_a_id <> student_b_id', name='ck_pair_scores_distinct_students'),
    sa.ForeignKeyConstraint(['matching_run_id'], ['matching_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_a_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_b_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_pair_scores_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_pair_scores_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matching_run_id', 'segment_id', 'student_a_id', 'student_b_id', name='uq_pair_scores_run_segment_pair')
    )
    op.create_index(op.f('ix_pair_scores_matching_run_id'), 'pair_scores', ['matching_run_id'], unique=False)
    op.create_index(op.f('ix_pair_scores_segment_id'), 'pair_scores', ['segment_id'], unique=False)
    op.create_index(op.f('ix_pair_scores_student_a_id'), 'pair_scores', ['student_a_id'], unique=False)
    op.create_index(op.f('ix_pair_scores_student_b_id'), 'pair_scores', ['student_b_id'], unique=False)
    op.create_index(op.f('ix_pair_scores_tenant_id'), 'pair_scores', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pair_scores_workspace_id'), 'pair_scores', ['workspace_id'], unique=False)
    op.create_table('room_assignments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('matching_run_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('room_label', sa.String(), nullable=True),
    sa.Column('assigned_students_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_score', sa.Float(), nullable=False),
    sa.Column('satisfaction_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('group_score >= 0.0 AND group_score <= 1.0', name='ck_room_assignments_group_score_range'),
    sa.ForeignKeyConstraint(['matching_run_id'], ['matching_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_room_assignments_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_room_assignments_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matching_run_id', 'segment_id', 'room_id', name='uq_room_assignments_run_segment_room')
    )
    op.create_index(op.f('ix_room_assignments_matching_run_id'), 'room_assignments', ['matching_run_id'], unique=False)
    op.create_index(op.f('ix_room_assignments_segment_id'), 'room_assignments', ['segment_id'], unique=False)
    op.create_index(op.f('ix_room_assignments_tenant_id'), 'room_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_room_assignments_workspace_id'), 'room_assignments', ['workspace_id'], unique=False)
    op.create_table('preference_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('source_form_response_id', sa.UUID(), nullable=True),
    sa.Column('has_preferences', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('q1_raw', sa.Text(), nullable=True),
    sa.Column('q2_raw', sa.Text(), nullable=True),
    sa.Column('q3_raw', sa.Text(), nullable=True),
    sa.Column('q4a_raw', sa.Text(), nullable=True),
    sa.Column('q4b_raw', sa.Text(), nullable=True),
    sa.Column('q5a_raw', sa.Text(), nullable=True),
    sa.Column('q5b_raw', sa.Text(), nullable=True),
    sa.Column('q6_raw', sa.Text(), nullable=True),
    sa.Column('q7_raw', sa.Text(), nullable=True),
    sa.Column('q8_raw', sa.Text(), nullable=True),
    sa.Column('q9_raw', sa.Text(), nullable=True),
    sa.Column('q10_raw', sa.Text(), nullable=True),
    sa.Column('q1_enc', sa.Float(), nullable=True),
    sa.Column('q2_enc', sa.Float(), nullable=True),
    sa.Column('q3_enc', sa.Float(), nullable=True),
    sa.Column('q4a_enc', sa.Float(), nullable=True),
    sa.Column('q4b_enc', sa.Float(), nullable=True),
    sa.Column('q5a_enc', sa.Float(), nullable=True),
    sa.Column('q5b_enc', sa.Float(), nullable=True),
    sa.Column('q6_enc', sa.Float(), nullable=True),
    sa.Column('q7_enc', sa.Float(), nullable=True),
    sa.Column('q8_enc', sa.Float(), nullable=True),
    sa.Column('q9_enc', sa.Float(), nullable=True),
    sa.Column('q10_enc', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_form_response_id'], ['form_responses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_preference_profiles_tenant_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_preference_profiles_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_profiles_student_id'), 'preference_profiles', ['student_id'], unique=False)
    op.create_index(op.f('ix_preference_profiles_tenant_id'), 'preference_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_preference_profiles_workspace_id'), 'preference_profiles', ['workspace_id'], unique=False)
    op.create_index('ux_preference_profiles_one_active', 'preference_profiles', ['student_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_preference_profiles_one_active', table_name='preference_profiles', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_preference_profiles_workspace_id'), table_name='preference_profiles')
    op.drop_index(op.f('ix_preference_profiles_tenant_id'), table_name='preference_profiles')
    op.drop_index(op.f('ix_preference_profiles_student_id'), table_name='preference_profiles')
    op.drop_table('preference_profiles')
    op.drop_index(op.f('ix_room_assignments_workspace_id'), table_name='room_assignments')
    op.drop_index(op.f('ix_room_assignments_tenant_id'), table_name='room_assignments')
    op.drop_index(op.f('ix_room_assignments_segment_id'), table_name='room_assignments')
    op.drop_index(op.f('ix_room_assignments_matching_run_id'), table_name='room_assignments')
    op.drop_table('room_assignments')
    op.drop_index(op.f('ix_pair_scores_workspace_id'), table_name='pair_scores')
    op.drop_index(op.f('ix_pair_scores_tenant_id'), table_name='pair_scores')
    op.drop_index(op.f('ix_pair_scores_student_b_id'), table_name='pair_scores')
    op.drop_index(op.f('ix_pair_scores_student_a_id'), table_name='pair_scores')
    op.drop_index(op.f('ix_pair_scores_segment_id'), table_name='pair_scores')
    op.drop_index(op.f('ix_pair_scores_matching_run_id'), table_name='pair_scores')
    op.drop_table('pair_scores')
    op.drop_index(op.f('ix_form_responses_workspace_id'), table_name='form_responses')
    op.drop_index('ix_form_responses_workspace_admission_submitted', table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_validation_status'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_tenant_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_submitted_at'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_student_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_students_workspace_id'), table_name='students')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_index(op.f('ix_students_segment_id'), table_name='students')
    op.drop_index(op.f('ix_students_phone_last4'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_rooms_workspace_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_tenant_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_segment_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_matching_runs_workspace_id'), table_name='matching_runs')
    op.drop_index(op.f('ix_matching_runs_tenant_id'), table_name='matching_runs')
    op.drop_index(op.f('ix_matching_runs_target_segment_id'), table_name='matching_runs')
    op.drop_index(op.f('ix_matching_runs_status'), table_name='matching_runs')
    op.drop_index(op.f('ix_matching_runs_created_at'), table_name='matching_runs')
    op.drop_table('matching_runs')
    op.drop_index(op.f('ix_workspace_form_links_workspace_id'), table_name='workspace_form_links')
    op.drop_index(op.f('ix_workspace_form_links_tenant_id'), table_name='workspace_form_links')
    op.drop_table('workspace_form_links')
    op.drop_index(op.f('ix_segments_workspace_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_tenant_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_workspaces_tenant_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_platform_audit_events_tenant_id'), table_name='platform_audit_events')
    op.drop_index(op.f('ix_platform_audit_events_event_type'), table_name='platform_audit_events')
    op.drop_index(op.f('ix_platform_audit_events_created_at'), table_name='platform_audit_events')
    op.drop_table('platform_audit_events')
    # ### end Alembic commands ###
