"""add_index_source_form_response_id

Revision ID: 59c3bb185e91
Revises: 8744d05f47e1
Create Date: 2026-05-29 05:36:22.131282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c3bb185e91'
down_revision: Union[str, None] = '8744d05f47e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_preference_profiles_source_form_response_id'), 'preference_profiles', ['source_form_response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_profiles_source_form_response_id'), table_name='preference_profiles')
    # ### end Alembic commands ###
