"""Add workspace_id index to matching_runs

Revision ID: e26a92a336a6
Revises: 518fbf2fb0e6
Create Date: 2026-05-28 07:14:00.277335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26a92a336a6'
down_revision: Union[str, None] = '518fbf2fb0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_matching_runs_workspace_id_id', 'matching_runs', ['workspace_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matching_runs_workspace_id_id', table_name='matching_runs')
    # ### end Alembic commands ###
